use std::ffi::OsStr;
use std::path::PathBuf;
use std::time::{Duration, UNIX_EPOCH};

use fuser::{
    Config, Errno, FileAttr, FileHandle, FileType, Filesystem, Generation, INodeNo, LockOwner,
    MountOption, OpenFlags, ReplyAttr, ReplyData, ReplyDirectory, ReplyEntry, Request,
};

const TTL: Duration = Duration::from_secs(1);
const ROOT: u64 = 1;
const DOCS: u64 = 2;
const HELLO: u64 = 3;
const README: u64 = 4;
const BOUNDARY: u64 = 5;
const BOUNDARY_SIZE: u64 = 1024 * 1024 + 1;
const HELLO_CONTENT: &[u8] = b"Biunivers Workspace mount probe\n";
const README_CONTENT: &[u8] =
    b"# Probe fixture\n\nThis tree is immutable and generated by the probe.\n";

fn inode(value: u64) -> INodeNo {
    INodeNo(value)
}

fn attr(ino: u64) -> Option<FileAttr> {
    let (kind, size, perm, nlink) = match ino {
        ROOT => (FileType::Directory, 0, 0o755, 3),
        DOCS => (FileType::Directory, 0, 0o755, 2),
        HELLO => (FileType::RegularFile, HELLO_CONTENT.len() as u64, 0o644, 1),
        README => (FileType::RegularFile, README_CONTENT.len() as u64, 0o644, 1),
        BOUNDARY => (FileType::RegularFile, BOUNDARY_SIZE, 0o644, 1),
        _ => return None,
    };

    Some(FileAttr {
        ino: inode(ino),
        size,
        blocks: size.div_ceil(512),
        atime: UNIX_EPOCH,
        mtime: UNIX_EPOCH,
        ctime: UNIX_EPOCH,
        crtime: UNIX_EPOCH,
        kind,
        perm,
        nlink,
        uid: unsafe { libc_getuid() },
        gid: unsafe { libc_getgid() },
        rdev: 0,
        blksize: 4096,
        flags: 0,
    })
}

unsafe extern "C" {
    #[link_name = "getuid"]
    fn libc_getuid() -> u32;
    #[link_name = "getgid"]
    fn libc_getgid() -> u32;
}

fn boundary_byte(position: u64) -> u8 {
    ((position * 31 + 17) % 251) as u8
}

fn read_slice(content: &[u8], offset: u64, size: u32) -> &[u8] {
    let start = usize::try_from(offset)
        .unwrap_or(usize::MAX)
        .min(content.len());
    let end = start.saturating_add(size as usize).min(content.len());
    &content[start..end]
}

struct ProbeFs;

impl Filesystem for ProbeFs {
    fn lookup(&self, _req: &Request, parent: INodeNo, name: &OsStr, reply: ReplyEntry) {
        let ino = match (u64::from(parent), name.to_str()) {
            (ROOT, Some("docs")) => DOCS,
            (ROOT, Some("hello.txt")) => HELLO,
            (ROOT, Some("boundary.bin")) => BOUNDARY,
            (DOCS, Some("readme.md")) => README,
            _ => {
                reply.error(Errno::ENOENT);
                return;
            }
        };
        reply.entry(&TTL, &attr(ino).expect("known inode"), Generation(0));
    }

    fn getattr(&self, _req: &Request, ino: INodeNo, _fh: Option<FileHandle>, reply: ReplyAttr) {
        match attr(u64::from(ino)) {
            Some(value) => reply.attr(&TTL, &value),
            None => reply.error(Errno::ENOENT),
        }
    }

    fn readdir(
        &self,
        _req: &Request,
        ino: INodeNo,
        _fh: FileHandle,
        offset: u64,
        mut reply: ReplyDirectory,
    ) {
        let entries: &[(u64, FileType, &str)] = match u64::from(ino) {
            ROOT => &[
                (ROOT, FileType::Directory, "."),
                (ROOT, FileType::Directory, ".."),
                (DOCS, FileType::Directory, "docs"),
                (HELLO, FileType::RegularFile, "hello.txt"),
                (BOUNDARY, FileType::RegularFile, "boundary.bin"),
            ],
            DOCS => &[
                (DOCS, FileType::Directory, "."),
                (ROOT, FileType::Directory, ".."),
                (README, FileType::RegularFile, "readme.md"),
            ],
            _ => {
                reply.error(Errno::ENOTDIR);
                return;
            }
        };

        for (index, (entry_ino, kind, name)) in entries.iter().enumerate().skip(offset as usize) {
            if reply.add(inode(*entry_ino), (index + 1) as u64, *kind, *name) {
                break;
            }
        }
        reply.ok();
    }

    fn read(
        &self,
        _req: &Request,
        ino: INodeNo,
        _fh: FileHandle,
        offset: u64,
        size: u32,
        _flags: OpenFlags,
        _lock_owner: Option<LockOwner>,
        reply: ReplyData,
    ) {
        match u64::from(ino) {
            HELLO => reply.data(read_slice(HELLO_CONTENT, offset, size)),
            README => reply.data(read_slice(README_CONTENT, offset, size)),
            BOUNDARY => {
                let start = offset.min(BOUNDARY_SIZE);
                let end = start.saturating_add(size as u64).min(BOUNDARY_SIZE);
                let bytes: Vec<u8> = (start..end).map(boundary_byte).collect();
                reply.data(&bytes);
            }
            ROOT | DOCS => reply.error(Errno::EISDIR),
            _ => reply.error(Errno::ENOENT),
        }
    }
}

fn main() {
    let mut arguments = std::env::args_os().skip(1);
    let first = arguments.next().unwrap_or_else(|| {
        eprintln!("usage: workspace-mount-probe [--allow-other] <mountpoint>");
        std::process::exit(2);
    });
    let (allow_other, mountpoint) = if first == "--allow-other" {
        let mountpoint = arguments.next().map(PathBuf::from).unwrap_or_else(|| {
            eprintln!("usage: workspace-mount-probe [--allow-other] <mountpoint>");
            std::process::exit(2);
        });
        (true, mountpoint)
    } else {
        (false, PathBuf::from(first))
    };
    if arguments.next().is_some() {
        eprintln!("usage: workspace-mount-probe [--allow-other] <mountpoint>");
        std::process::exit(2);
    }

    let mut config = Config::default();
    config.mount_options.extend([
        MountOption::RO,
        MountOption::FSName("biunivers-workspace-probe".to_owned()),
        MountOption::NoAtime,
    ]);
    if allow_other {
        config
            .mount_options
            .push(MountOption::CUSTOM("allow_other".to_owned()));
    }

    if let Err(error) = fuser::mount(ProbeFs, &mountpoint, &config) {
        eprintln!("workspace mount probe failed: {error}");
        std::process::exit(1);
    }
}
